name: Python application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]


jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      ai_service: ${{ steps.filter.outputs.ai_service }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ai_service:
              - 'ai-service/**'
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      working-directory: ./ai-service
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest and coverage
      working-directory: ./ai-service
      run: |
        pytest --cov=app --cov-report=xml --cov-report=html --cov-report=term-missing
    - name: Check Code Coverage
      working-directory: ./ai-service
      run: |
        coverage report --fail-under=80
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: ai-service/htmlcov/
